### ISSUE TITLE
Popen FileNotFoundError

### ISSUE THREAD

**Issue by MKatereggaExigent** [achilleas-michos/pdf-text-extraction#3]
I found pdf-text-extraction and is perfect for the project I am currently working on. I tried to test it by running:

 `run process_document.py`

But I get the error:

`FileNotFoundError: [Errno 2] No such file or directory: 'pdftohtml': 'pdftohtml' `

This error is from: `extraction/pdf_to_xml/converter/converter_poppler.py`

**Comment by achilleas-michos** [comment]
Hi,

This is a command line utility of linux which is installed by default in most distribution. So I assume that you are using windows.
I propose that you either activate the linux sub-system of windows and run it on linux command line or change to the pdfminer extraction.
The latter can be done by changing this line https://github.com/achilleas-michos/pdf-text-extraction/blob/39f0a92189434ba5c4ae95dbd0c9f0ff117311eb/extration/pdf_to_xml/convert2xml.py#L8

To: from extration.pdf_to_xml.converter.converter_miner import Converter

**Comment by MKatereggaExigent** [comment]
Thank you @achilleas-michos
